services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
        depends_on:
            - redis
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # db mysql
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_USER: ${DB_USERNAME:-db_user}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

networks:
    laravel:
        driver: bridge
