services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./app:/var/www
        depends_on:
            - redis
            - db
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # db postgres
    db:
        image: postgres:14-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
            POSTGRES_USER: ${DB_USERNAME:-db_user}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel
        platform: linux/amd64  # Força o uso da arquitetura amd64

networks:
    laravel:
        driver: bridge
